version: '3'

services:
  ntfy:
    container_name: NOTIFY
    image: ntfyme
    build:
      context: .
      dockerfile: Dockerfile-ntfy
    networks:
      public_bridge:
    environment:
      doppler_token: $DOPPLER_TOKEN
      TZ: Europe/Bucharest
    volumes:
      - "/mnt/external/alex/notify:/app/database"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alexirimiaonline.rule=Host(`fuelprice.alexirimia.online`)"
      - "traefik.http.services.alexirimiaonline.loadbalancer.server.port=3110"
      - "traefik.http.routers.alexirimiaonline.middlewares=traefik-https-redirect"
      - "traefik.http.routers.alexirimiaonline.tls=true"
      - "traefik.http.routers.alexirimiaonline.tls.certresolver=le"
      - "traefik.http.routers.alexirimiaonline.tls.domains[0].main=alexirimia.online"
      - "traefik.http.routers.alexirimiaonline.tls.domains[0].sans=*.alexirimia.online"

networks:
  public_bridge:
    name: public_bridge
    external: true