version: '3'

services:
  ntfy:
    container_name: NOTIFY
    image: ntfyme:2
    build:
      context: .
      dockerfile: Dockerfile-ntfy
    ports:
      - "0.0.0.0:3110:3110"
    environment:
      doppler_token: $DOPPLER_TOKEN
      TZ: Europe/Bucharest
    volumes:
      - "alex-ntfy:/app/database"
    restart: always
volumes:
  alex-ntfy:
    external: true