version: '3'

services:
  ntfy:
    container_name: NOTIFY
    build:
      context: .
      dockerfile: Dockerfile-ntfy
    ports:
      - "0.0.0.0:3110:3110"
    environment:
      - server_exchange=https://ntfy.sh/cursvalutaralexyrm
      - server_fuelprice=statia
      - server_squash=https://ntfy.sh/squashcubaietii
      - squash_cookies={"cookieconsent_status":"dismiss","sqzd":"FtooX61*z"}
      - squash_payload={"eeee":"alex_irimia@ymail.com","pppp":"imposibildeaflat","e_mail":""}
      - TZ=Europe/Bucharest
    volumes:
      - "/mnt/external/alex/notify:/app/database"
    restart: always