version: '3'

services:
  ntfy:
    container_name: NOTIFY
    build:
      context: .
      dockerfile: Dockerfile-ntfy
    ports:
      - "0.0.0.0:3110:3110"
    environment:
      - server_exchange=https://ntfy.sh/cursvalutaralexyrm
      - server_fuelprice=statia
      - TZ=Europe/Bucharest
    volumes:
      - "/mnt/external/alex/notify:/app/database"
    restart: always