version: '3'

services:
  ntfy:
    container_name: NOTIFY
    build:
      context: .
      dockerfile: Dockerfile-ntfy
    ports:
      - "0.0.0.0:3110:3110"
    volumes:
      - "./database:/app/database"
    restart: always